### ISSUE TITLE
Book4_Power-of-Matrix，所有PDF文件的标题文本错了，应为矩阵力量

### ISSUE THREAD

**Issue by tobe27** [Visualize-ML/Book4_Power-of-Matrix#1]
![image](https://user-images.githubusercontent.com/42547092/182285048-7925669b-a178-4bf2-99a1-990038ad329b.png)

**Comment by Visualize-ML** [comment]
谢谢指出！已经修改，并更新

**Comment by Visualize-ML** [comment]
感谢你对鸢尾花书的支持，清华社安排了赠书活动。

活动页面：
https://zhuanlan.zhihu.com/p/622091048
