### ISSUE TITLE
实体书的纸不适合记笔记。

### ISSUE THREAD

**Issue by OrangeFish-KSL** [Visualize-ML/Book4_Power-of-Matrix#101]
如题，纸质量很好。但是写出来的字不易干。

**Comment by Visualize-ML** [comment]
谢谢你的反馈。

我也有和你一样的问题。为了保证彩色印刷，我们用了比铜版纸还要好的纸。

我现在也只能用铅笔在纸上写写画画。用水笔写字的话，需要用白纸隔着。

我会和出版社反馈，看看有没有好的解决方案。谢谢你。

Cheers
