### ISSUE TITLE
建议：公式 2.39 应该附带解释且图 2.16 应该放在公式 2.39 下方

### ISSUE THREAD

**Issue by walkerlala** [Visualize-ML/Book4_Power-of-Matrix#104]
<img width="724" alt="snipast" src="https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/11005974/fedf868d-1960-43ad-bfa8-145c973966d4">

这个地方有两个小建议：
1. 公式 2.39 应该附带解释，因为向量内积的几何表示并不是很“理所当然”，要从 a1b1 + a2b2 直接得到 ||a||||b||cos_theta 并不是很“直观”，实际上我看到这个地方想了很久，为什么向量内积，也就是 a1b1 + a2b2 等于 ||a||||b||cos_theta 。后来才想明白，如果用 2.16 图去理解，以 b 作为坐标“基础”，那么 a 在垂直于 a 的轴上，大小为 0，因此那个轴的乘积为 0，所以两者的内积才等于 (||a||cos_theta) ||b|| ，也就是书中给的 2.39 式。我看后面将向量叉乘，也是直接给的公式，让我一头雾水。还是说后面有讲？

2. 另外，排版上，图 2.16 应该放在公式 2.39 的下方，比较符合人的阅读习惯。一开始我看得快的时候，没发现这张图。

**Comment by Visualize-ML** [comment]
谢谢你的建议，确实，引出这两个公式的时候要铺垫一下。请继续批评指正。

中秋快乐！

Cheers,
James
