### ISSUE TITLE
CH

### ISSUE THREAD

**Issue by chuixuewan** [Visualize-ML/Book4_Power-of-Matrix#106]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/51576471/3c40cc8a-5f2b-4901-aab0-c66509bc0e46)
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/51576471/44edd7ef-44cf-43ce-8365-e498441f70bc)
公式符号不一致

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改，电子版没有同步。请继续批评指正
