### ISSUE TITLE
Page 17 | Chapter 05: 5.4节公式48中的一个笔误，最后的x应该为b

### ISSUE THREAD

**Issue by jiankang-star** [Visualize-ML/Book4_Power-of-Matrix#108]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69316331/6a8d8879-62da-4f73-9728-b70558ed7321)

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改，PDF不再同步。

请继续批评指正。

Cheers
