### ISSUE TITLE
Page 34 | Chapter 05: 笔误“细高的X显然不存在转置”

### ISSUE THREAD

**Issue by jiankang-star** [Visualize-ML/Book4_Power-of-Matrix#109]
“细高的X显然不存在转置”，这里的“转置”应该是“矩阵的逆”吧？
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69316331/0e476940-1893-4a26-9e20-0bb4d3bac5f2)

**Comment by Visualize-ML** [comment]
谢谢你，确是笔误，纸质书已经纠正，PDF草稿没有同步。

请继续批评指正。

Cheers
