### ISSUE TITLE
Book4_Ch15_Page11

### ISSUE THREAD

**Issue by Hurricane-k** [Visualize-ML/Book4_Power-of-Matrix#11]
图10中，（从左往右数）第一个绿色矩阵（即X转置乘以X）的维度应该是DxD，或者根据前文：如图10所示，矩阵X乘以X转置进行特征值分解...，两处描述有悖

**Comment by Hurricane-k** [comment]
您这一块要描述的左奇异向量矩阵，所以推测应该是图10中，应该讲X转置乘以X改成X乘以X转置

**Comment by Visualize-ML** [comment]
谢谢你，图10确实有误，应该是XX^T，已经修改。请多多批评
