### ISSUE TITLE
Page 10 | Chapter 6 分块矩阵 | Book 4《矩阵力量》图7有瑕疵

### ISSUE THREAD

**Issue by pzl-lab** [Visualize-ML/Book4_Power-of-Matrix#110]
Page 10 | Chapter 6 分块矩阵 | Book 4《矩阵力量》的图7展示矩阵的乘法第二视角：外积展开的时候，示意图 $a_i @ b^{(i)}  = a_i b^{(i)} $，对于b行向量取的是m=3，也就是3列，最后的乘积示意图却是4列（意思表达出来了，但是图文不统一）您公开这样的书给大家，真的太厉害了

**Comment by Visualize-ML** [comment]
纸质书已经修改，请继续批评指正。
