### ISSUE TITLE
矩阵力量纸质书第一版第四章P91图4.14有错误

### ISSUE THREAD

**Issue by leonanor98** [Visualize-ML/Book4_Power-of-Matrix#111]
矩阵乘法规则A@B=C这个图，C的结果乱了。

![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/44010982/3a1ad939-d33d-488e-9c87-ea7ed687a8bd)

**Comment by Visualize-ML** [comment]
谢谢你，排版确实发生了失误。请继续批评指正。

Cheers,
