### ISSUE TITLE
《矩阵力量》纸质书 Chapter 4.6 Page92 | 矩阵乘法的“第二视角”栏目中有不严谨的地方

### ISSUE THREAD

**Issue by ZiyuLin-DASHi** [Visualize-ML/Book4_Power-of-Matrix#112]
该栏目的第一句话为：“矩阵乘法的第二视角叫做外积展开”。
个人认为这里的“外积”指的是“张量积”而不是“叉积”，所以叫“张量积”会更准确且不容易让人迷惑一些。

**Comment by Visualize-ML** [comment]
确实是，外积这个词在不同语境有不同含义，应该更明确说明。请继续批评，谢谢。

**Comment by ZiyuLin-DASHi** [comment]
您好，再次打扰您，我对一个地方有些疑惑。Chatper13.4 P325 “**谱分解格拉姆矩阵**”栏目。
在公式13.33下面一行，“**由于yj是单位矩阵**”，您是否想说“**由于vj是单位向量**”。

**Comment by Visualize-ML** [comment]
不打扰，欢迎批评指正！这个确实写错了，你是对的！谢谢你

**Comment by ZiyuLin-DASHi** [comment]
您的回复太快了！
Chapter14.5 P345 图14.7，好像v1和v2标反了。

**Comment by ZiyuLin-DASHi** [comment]
纸质书的P393的“**如图17.24(a)所示**”多打了一个2，P422的“**式(18.4w5)也等价于**”应该是(18.46)，我看电子版上面没有类似的问题，可能已经更改，冒昧打扰。

**Comment by Visualize-ML** [comment]
谢谢你，v1和v2确实反了。

后面排版确实有些小问题。请继续批评指正！

鸢尾花书有纠错赠书活动，下一批次赠送《编程不难》 + 签名卡。把你加到赠书名单里吧！请给我的邮箱发送你的邮寄信息。邮箱在PDF左下角。

Cheers

**Comment by ZiyuLin-DASHi** [comment]
非常感谢！已经给您发了邮件。

**Comment by ZiyuLin-DASHi** [comment]
Chapter18.2 P411 "梯度平行”栏目
![屏幕截图 2023-11-13 190143](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/118437496/2d836531-316b-48f1-b36d-4491741dba7d)
红色箭头所指处，似乎少了一个“是”。
