### ISSUE TITLE
纸质书第五章图5.14有错

### ISSUE THREAD

**Issue by leonanor98** [Visualize-ML/Book4_Power-of-Matrix#113]
A@x=b这个图，b应该是一个列向量，图5.14印成一个点成标量了。
![微信图片_20231101155239](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/44010982/a388bdf2-1f13-4f9e-b66d-c4fd30ee81e1)

**Comment by Visualize-ML** [comment]
你是对的，这一点确实有点绕，我是想用一个方块表达列向量，A隐藏了行数，所以就没有完整画出b行数。

确实需要在图中说明b是一个列向量。

请继续批评指正

**Comment by hxy2321548628** [comment]
我觉得没错吧，作者在书中写了，粗体小写符号代表列向量，图中的b如果是标量的话应该不是粗体，所以没错
