### ISSUE TITLE
Page 8 | Ch15: 图5中的U矩阵没有标出U1和U2

### ISSUE THREAD

**Issue by jiankang-star** [Visualize-ML/Book4_Power-of-Matrix#114]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69316331/d1b2c179-734d-4f5f-a2dd-ec79a7f142ff)

**Comment by Visualize-ML** [comment]
谢谢你，分块矩阵转置确实应该标出来！请继续批评指正。
