### ISSUE TITLE
Ch25 图11

### ISSUE THREAD

**Issue by 17314796423** [Visualize-ML/Book4_Power-of-Matrix#126]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/49507327/87e88794-cac1-4482-844b-18ad6cb524cd)
这里的Σ是不是准确来说是Σ的逆，Σ的信息其实隐含在这个椭圆里的意思

**Comment by Visualize-ML** [comment]
你说得对，无论是多元高斯分布PDF，马氏距离，都是Sigma的逆。为了简便，就省略了矩阵逆

**Comment by 17314796423** [comment]
ok
