### ISSUE TITLE
Book_3_Chapter 8.7 公式 8.40

### ISSUE THREAD

**Issue by perfectnihil** [Visualize-ML/Book4_Power-of-Matrix#127]
双曲线平移后的渐近线公式是否写错了?

**Comment by perfectnihil** [comment]
![1705998109743](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/6982299/0aa48813-1dc0-4d6f-bbe0-59b324db779a)
原文公式

**Comment by perfectnihil** [comment]
二：Streamlit_BK3_Ch11_03.py 代码缺失

**Comment by Visualize-ML** [comment]
谢谢你，我查一下哈。请继续批评指正
