### ISSUE TITLE
chapter 12 印刷问题

### ISSUE THREAD

**Issue by hxy2321548628** [Visualize-ML/Book4_Power-of-Matrix#132]
up，图中的印刷是不是有点问题
![7c7b04c06ca05cebb50ecb73c54c1ec](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/149643090/db6cf960-ea40-4df2-a530-29e4efb3055f)

**Comment by Visualize-ML** [comment]
是的，应该是下标。谢谢你
请继续批评指正
