### ISSUE TITLE
bk4_chapter1_figure1.11有误

### ISSUE THREAD

**Issue by ZhouSuii** [Visualize-ML/Book4_Power-of-Matrix#137]
《矩阵力量》23年7月第二版chapter1图1.11鸢尾花成对特征散点图中纵坐标标签重复

**Comment by ZhouSuii** [comment]
![51](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/97154327/2aac5bc4-e506-45d5-b3e9-0888056f0c53)

**Comment by Visualize-ML** [comment]
谢谢，确实重复了。请继续批评指正。
