### ISSUE TITLE
Ch1_p16_Fig19 对角矩阵元素颜色

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#139]
SVD分解之后得到对角矩阵 $\Sigma$，非对角元素是不是用灰色或者白色填充更清楚？

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/be584ea9-86e2-435c-8ba2-668a49bf39b8)

**Comment by Visualize-ML** [comment]
确实，谢谢你。
