### ISSUE TITLE
Ch4_p14_矩阵乘法 线性映射解读

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#141]
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/f50efb9d-ff88-4fb1-91ab-8bf9608c16e8)

这个段落读起来总感觉不是很完整，稍作引申的话，可以把向量 $x, b$ 替换为 $v_B, w_B$， 分别是向量空间 $V, W$的基向量。如果线性映射 $f(x) = Ax$ 可以使 $v_B$ 映射到 $w_B$， e.g. $f(v_B) = Av_B = w_B$，那么对于所有 $v \in V$， 都可以通过 $f(v) = Av =w$ 将其映射到 $w \in W$，因为 $v, w$ 本身就是基向量线性组合来的。表面上矩阵 $A$ 实现了向量的线性映射，实际上是完成了由这两个向量扩张成的线性空间之间维度的转换。

我不确定这样理解是不是合理，就是一说到矩阵先想到维度转换，如果完全不提会感觉少了点什么。。。

**Comment by Visualize-ML** [comment]
谢谢你，确实缺少一点过度。
