### ISSUE TITLE
Ch6_p17_Fig. 19 标注错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#142]
Fig 19 矩阵C右下角block标注应为 $C_{2,2}$

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/42de9cb3-b58f-42e3-8782-82ae35dddd68)

**Comment by Visualize-ML** [comment]
纸质已经修改，请继续批评指正。
