### ISSUE TITLE
Ch9_p11 一处上标错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#143]
前文有定义矩阵 $V \in \mathbb{R}^{D \times D}$，所以最后一个列向量应为 $v^{(D) \text{T}}$

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/76d1acfc-11f9-42e8-acd7-bd02e3e3bcbe)

**Comment by Visualize-ML** [comment]
确实是D，谢谢
