### ISSUE TITLE
Ch9_p13_Eq.(45) 等式中有错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#144]
eq(45) 红色方框这部分，lhs的列向量内是两个标量，rhs是两个向量投影（向量），等式不能成立；应该把rhs去掉，或者左乘 $V^{-1}$？

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/1b39162e-1bd4-405e-b77c-6a4231da8467)

**Comment by Visualize-ML** [comment]
proj那块写错了，原来用proj代表标量投影，忘了改了。
