### ISSUE TITLE
Ch10_p27_Fig.38-42 图像标题

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#145]
图38标题里第二个 $X$ 是多余的
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/8335616d-cb56-4679-bc54-6a044d35b006)

图39 应为 四特征数据矩阵 $X_{150×4}$ 向 $v_1$ 方向的标量投影 $z_1$ 乘 $v_1^T$ 二次投影 得到 $X_1$
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/2df2bf20-b0b7-48bd-89b5-e954a8340732)

同理图42标题里也多了一个 $X$

**Comment by Visualize-ML** [comment]
谢谢你！你先提着，我后面会一个个逐项查一遍！

再次感谢，这个肯定要再赠一套“数学三剑客”。我已经给出版社发消息了。

Cheers,
Jimmy

**Comment by shuoChenTHU** [comment]
> 谢谢你！你先提着，我后面会一个个逐项查一遍！ 再次感谢，这个肯定要再赠一套“数学三剑客”。我已经给出版社发消息了。 Cheers, Jimmy

那太感谢啦！我这几天晚上都会拜读这套书，遇到疑似错误的地方就po上来，希望不会太打扰你 :D

**Comment by Visualize-ML** [comment]
希望书的内容没有辜负期待，再次感谢你的各种建议！

Cheers

**Comment by shuoChenTHU** [comment]
> 希望书的内容没有辜负期待，再次感谢你的各种建议！ Cheers

书里内容对我帮助太大了，非常感谢开源分享！三剑客系列纸质书我家人收到了，再次感谢！现在坐等作者签名卡 :D

**Comment by shuoChenTHU** [comment]
> 希望书的内容没有辜负期待，再次感谢你的各种建议！ Cheers

后面有时间了我再继续看其他几本书，感谢作者愿意花时间看我提的一堆拙见，希望对提升其他读者阅读体验有帮助！
