### ISSUE TITLE
Ch11_p13_Eq.(30) 主特征值问题

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#146]
这里求出方阵特征方程的两个实根以后，为什么没有直接把较大的值作为主特征值赋给 $\lambda_1$?

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/a7179629-8a5a-4197-8948-745b5baf11f8)

**Comment by Visualize-ML** [comment]
这个是根据numpy的eig函数来的，它也没按大小排列...

**Comment by shuoChenTHU** [comment]
> 这个是根据numpy的eig函数来的，它也没按大小排列...

顺序也许确实不是很重要，我今天刚看了另一本教材，里面的特征值也没有特意按大小排列，而且特征值有正负，说不好怎么排序最正确。但是我确实上过一门课，习题里算特征值（都是正的）和特征向量的时候是按大小顺序来，可能因为奇异值的顺序太重要了，有的教授算特征向量的时候也是按大小顺序来。
