### ISSUE TITLE
Ch12_p13_Eq.(35)-(37) 验证过程

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#147]
这里的三个等式是为了验证前面的文字描述，然而因为忽略了中间的计算过程，导致好像并没有验证什么，不如直接写：
通过简单的计算，可验证
```math
\frac{\boldsymbol{r}_i \cdot \boldsymbol{r}_j}{\left\|\boldsymbol{r}_i\right\|\left\|\boldsymbol{r}_j\right\|}=\cos \theta_{i,j}$$
```
这样就没必要罗列3个只有结果的等式了。

或者可以三个等式中各展开多写一步计算过程（分子就是加减法，分母二范数都是1），这样读起来会通顺一些。不然这一块整个显得很冗余。。。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/11204b66-9a33-430d-aed2-13819845a351)

**Comment by Visualize-ML** [comment]
确实可以更简洁些。
