### ISSUE TITLE
Ch12_p20_Eq.(53) 下标错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#148]
有两处出现下标typo，应该是 $\boldsymbol{r}_1, \boldsymbol{r}_2, \cdots$

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/75b4535a-9a2f-4581-bba3-d41365f60aa9)

**Comment by Visualize-ML** [comment]
确实写错了。
