### ISSUE TITLE
Ch13_p12_Eq.(26) 少了n-1次幂 

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#149]
第二项需要把n-1次幂补充上吧

$$
\boldsymbol{A}^n=\boldsymbol{V} \boldsymbol{D} \boldsymbol{V}^{-1} \left(    \boldsymbol{V} \boldsymbol{D} \boldsymbol{V}^{-1}   \right)^{n-1}
$$

然后中间的 $\boldsymbol{V}^{-1} \boldsymbol{V}$ 显然都会消掉，就可以得到

$$
\boldsymbol{A}^n=\boldsymbol{V} \boldsymbol{D} \boldsymbol{V}^{-1} \left(    \boldsymbol{V} \boldsymbol{D} \boldsymbol{V}^{-1}   \right)^{n-1} = \boldsymbol{V} \boldsymbol{D}^n \boldsymbol{V}^{-1}
$$

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/d174abae-b4af-42c4-82e6-bbf2e87d435f)

**Comment by Visualize-ML** [comment]
纸质书已经修改。
