### ISSUE TITLE
Ch14_p10_Eq. (41) (42) 表述问题

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#152]
> 鸡、兔比例非负，且两者之和为1。因此选择 $v_2$ 来计算 $\pi$ 

我第一遍看没有直接get到 $\pi$  是 $v_2$ 的比例缩放，反而回去推导 $\pi$ 的解析式， 想看一下哪里可以代入 $v_2$，后来才反应过来完全没有必要去推导。所以改成这样读者更好理解：

**鸡、兔比例非负，且两者之和为1。因此选择将 $v_2$ 按比例缩放得到 $\pi_{\inf}$**
 （这里以及上文的几个eq，把平稳状态的 $\pi$ 写成 $\pi_{\inf}$ 可能会直观，比较容易和初始状态区分开来）

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/8295194d-008d-4672-aa41-777ae01afe9a)

另外我发现Bk4_Ch14_02.py 计算出来的矩阵 $V$ 的特征向量，$`v_2`$ 两个元素都是负数，但是eq(41)给的都是正数，所以不确定能否直接用正负来判断该选择哪个特征向量进行缩放。参考[这个链接](https://www.fsb.miamioh.edu/lij14/400_slide_mc.pdf)中的推导过程，更根本的原因是 k 趋近无穷时，绝对值小于1的特征值趋近为0，所以应该选择绝对值为1的特征值对应的特征向量，进行缩放以得到 $\pi_{\inf}$。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/69e5e327-1735-4af5-bbdc-3ae74cd3fea4)

**Comment by Visualize-ML** [comment]
最开始是要介绍幂迭代，后来删掉了。下一版可以补充回来。
