### ISSUE TITLE
Ch17_p5_Eq. (8) 文字描述中格式错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#153]
Eq (8) 下方文字描述，一阶导数 $f^{'}(x)$ 的prime看起来很奇怪， 不知道是不是误用了中文字符的 ‘ 导致的 

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/c9d917e6-424d-461f-8593-8ba89feb3206)

**Comment by shuoChenTHU** [comment]
同一章p8 Eq. (23) 大括号的下标是不是没必要，要么直接写成偏微分的下标 $\partial f({x_P})$，要么把偏微分分子省略成 $\partial f$，然后大括号外面下标  $x_P$ ？
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/9031cce9-33ee-4dcb-bdfb-fc0d1a9076fe)

**Comment by shuoChenTHU** [comment]
同一章 p.22 Eq. (57)
完整的解析式是不是这样：$` t(x_1, x_2) = 12 x_1 + 12 x_2 + 9 `$
只是 $x_1=0$ 所以恰好省略了，我不确定是不是写完整比较好。。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/db3df3c7-e5d6-47c5-9ecd-c800c1007e30)

**Comment by shuoChenTHU** [comment]
p.23 Fig. 18 图里 $x_1 x_2$平面内各有2条坐标轴，但是没有标注数值，读者会默认是  $x_1 = 0$  或者 $x_2 = 0$，但并不是，切点投影下去的点才是，而且显然不在画出来的坐标轴上。 可以考虑微调一下，如果坐标轴在图里没有什么实际意义，不如用一个更大的浅色系平面代替。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/4b72def8-24d9-4264-92cb-804d6b1b84f6)

**Comment by Visualize-ML** [comment]
梯度向量确实需要统一格式。
