### ISSUE TITLE
Ch18_p4_p5 一些细节问题

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#154]
优化问题的formulation和book3一样用了 $` \text{argmin} f(x) `$，但是个人感觉英文教材和文献里更多的是直接用  $` \min f(x) `$ 或者 $` \text{minimize} f(x) `$，似乎更强调优化的过程。在Algorithm里用到某一步优化结果的时候会用  $` \text{argmin} `$。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/d62f04b7-479b-432a-bab4-6dfa9d743475)

**Comment by shuoChenTHU** [comment]
然后就是Lagrangian function 确定不用花体 $\mathcal{L}$ 么，理由同上，好像英文文献里这种表达更常见，可能是为了和其他各种operator区分开

**Comment by shuoChenTHU** [comment]
从p5开始，有很多关于 $\nabla f(x)$ 和 $\nabla h(x)$ 以及 $\nabla g(x)$ 方向的讨论，但是文中好像没有明确指出 $\nabla f(x)$ 的方向是上山，趋向极大值；反向是下山。虽然是显而易见的，但是多提一句读者就更容易理解。

**Comment by shuoChenTHU** [comment]
还是p.5，有提到 Eq. (7)(8) 对于读者来说不易理解，我个人非常推荐下面这个动态视频。总之就是醍醐灌顶，建议每一个初学者都看一下，作者可以考虑把链接放书里：
油管：https://www.youtube.com/watch?v=5A39Ht9Wcu0
b站也有同一个视频：https://www.bilibili.com/video/BV1vP4113729/

**Comment by shuoChenTHU** [comment]
p.15 Fig. 13(a) 指向外侧的梯度向量应该是 $\nabla g(x)$ 不是 $\nabla h(x)$
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/891850b1-4eb5-485c-b3cb-a58be227c551)

**Comment by Visualize-ML** [comment]
这些意见确实很好！这个issue先开着一下，我想想怎么修改。
