### ISSUE TITLE
Ch18_p.15 Fig. 13(a) 标注错误

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#155]
p.15 Fig. 13(a) 指向外侧的梯度向量应该是 $\nabla g(x)$ 不是 $\nabla h(x)$

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/891850b1-4eb5-485c-b3cb-a58be227c551)

**Comment by Visualize-ML** [comment]
确实标反了，谢谢你！
