### ISSUE TITLE
Ch18_p17. Eq. (22) KKT条件 极小值标注

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#156]
> 极小点 x 出现位置满足以下条件：
>  ![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/76e3ab84-f3aa-402a-a3e3-f71ed00b2501)

p17. Eq. (22) 及文字描述部分，建议给满足KKT的 极小值加上星标， 类似的还有eq (23)-(28)中的极值
Eq. (27) (28) 另一种矩阵乘法形式（把 $\lambda$ 写成向量）也很常见，可以考虑提一下。

```math
\left\{\begin{array}{l}
\nabla f(\boldsymbol{x^*})+\lambda^* \nabla g(\boldsymbol{x^*})=0 \\
g(\boldsymbol{x^*}) \leq 0 \\
\lambda^* \geq 0 \\
\lambda^* g(\boldsymbol{x^*})=0
\end{array}\right.
```

**Comment by Visualize-ML** [comment]
谢谢你的建议！
