### ISSUE TITLE
Ch19_p17_Fig.15 补充描述

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#158]
这张图里因为没有坐标系，不太容易看出来两个向量 $\mu_1, \mu_2$ 张成的平面是平行于还是垂直于还是斜切电脑屏幕。
也许这并不重要，因为不要求 $a$  垂直于平面 $\mu_1 \mu_2$ ，但是对读者来说，多一点文字或者图形解释就少一些干扰信息。。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/3a378363-4b33-4cab-a170-0842a48cf665)

**Comment by Visualize-ML** [comment]
确实和坐标系没关系，但是有必要交代一些背景信息。
