### ISSUE TITLE
Ch20_p27_Eq. (82) 切向量推导过程

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#159]
这个地方相当于直接给了解析式，没有写推导过程，有什么快捷的方法直接得到切向量 $\tau$ 么? 

根据向量指向比较容易判断符号，但是为什么先对 $x_2$ 求偏导，然后是 $x_1$，是利用 $\boldsymbol{\tau} \cdot \boldsymbol{n} = 0$ 直接看出来的嘛？ 

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/2c368a28-63cc-4d72-8640-5f9687a02c50)

**Comment by Visualize-ML** [comment]
是的，这个切向量有无数个；我们选择比较方便理解的那个。

**Comment by shuoChenTHU** [comment]
> 是的，这个切向量有无数个；我们选择比较方便理解的那个。

那是否可以强调一下切向量之一 $\tau$ 为 .... .... ？因为切向量可以指向垂直于法向量平面内的任一方向，不加”之一“的话，读者可能会纠结怎么会有一个确定的解呢
