### ISSUE TITLE
Ch21_p18 Fig. 11-14 举例时没有把函数解析式给出来

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#161]
> 举个例子
继续采用《数学要素》一书中反复出现的多极值曲面的例子。
图 11 为曲面平面等高线。图中，深绿色线代表fx1(x1, x2) = 0，深蓝色线代表fx2(x1, x2) = 0。两
个颜色线交点标记为 ×。也就是说，图中 × 对应的位置为梯度向量为0。

这个例子是紧挨着上面用Hessian顺序主子式来判断驻点类型，上面 $\boldsymbol{H}$ 还是4个常数 a b c d，例子里就突然变成了非线性的曲面二阶偏微分，跨度有点大（可能是我看太快了一时没反应过来。。）。

建议展示图11-14之前，再把 Ch16_p4_Eq. (3) 挂出来一下，这样读者思维转换比较容易。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/f909015c-06d9-4685-b2ae-fe8d324c5143)

**Comment by Visualize-ML** [comment]
速度好快啊！看到第21章了！谢谢你提了这么多好建议！
