### ISSUE TITLE
C22_p4 Eq.(1) 随机变量notation

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#162]
> 列向量 $x_j$ 对应随机变量 $X_j$。

22.4里随机变量 $X_j$ 被定义成了列向量，
但是20.4提到高斯分布 PDF的时候， $X_j$ 还是一个列向量中的一个随机变量

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/63c2d5b4-37a9-4021-aead-dcc02e7f75bd)

到后面又变成了列向量中的一个元素
![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/fd18f731-5811-4368-a7ce-4eb5f7d259e5)

在23.1 p5 区分符号的部分，也没有特别强调大写 $X_j$ 的不同含义。

**Comment by Visualize-ML** [comment]
谢谢你。
