### ISSUE TITLE
C22_p7 \mu_X 下标显示问题

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#163]
$\boldsymbol{\mu}_X$ 在公式中显示没问题，但是文字描述中看起来不像是下标，有细微差别。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/aa7c605d-2908-44da-aa63-05e4ff00d071)

**Comment by Visualize-ML** [comment]
已经修改，谢谢。
