### ISSUE TITLE
C23_p16 一处表达不清

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#165]
> 格外注意，大家不要留下错误印象，x1 或x(1) 就是u1 或v1 的方向重合。

是想说 
**大家不要留下错误印象，认为 x1 或x(1) $\textcolor{red}{就一定与}$ u1 或v1 的方向重合。** ？

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/c54be88c-aaa3-463d-b1a9-f80ec9a2dfc2)

**Comment by Visualize-ML** [comment]
谢谢！
