### ISSUE TITLE
C24_p12 U V 列向量 / 行向量 下标

### ISSUE THREAD

**Issue by shuoChenTHU** [Visualize-ML/Book4_Power-of-Matrix#166]
从这里开始出现了大量 包含underscore的下标，尤其是在表示 $\boldsymbol{V}$ 的行向量， $\boldsymbol{U}$ 的列向量，还有特征值的时候。如果有必要用这种形式标注，应该加一句注解提示一下读者。

![grafik](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/102961908/f298ba8e-4880-4d1c-bd0b-79650dabadf2)

**Comment by Visualize-ML** [comment]
确实有必要，谢谢你。
