### ISSUE TITLE
formula erro

### ISSUE THREAD

**Issue by kingwe-stack** [Visualize-ML/Book4_Power-of-Matrix#168]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/128909306/ef66c0c0-49f2-4c2e-b6ce-301e16bbbd11)
formula 58 ,the right one is ||Xv||/||v||

**Comment by Visualize-ML** [comment]
这个没有问题，v是单位向量所以消去；x仅仅是非0向量
