### ISSUE TITLE
Page 5 | Chapter 17 多元函数微分 | Book 4《矩阵力量》关于“二次型”的表述疑问

### ISSUE THREAD

**Issue by suye0620** [Visualize-ML/Book4_Power-of-Matrix#17]
![image](https://user-images.githubusercontent.com/71215104/232316314-23f3c60e-1d24-4005-84c8-e967b12b5306.png)
![image](https://user-images.githubusercontent.com/71215104/232316411-e32f756c-58a5-4780-ae07-314230e8873a.png)
我觉得此处“二次型”这部分表述有问题，这里定义了一个xTQx形式的多元函数，说“给定如下二次型”，然后分成Q为常数矩阵/对称矩阵考虑求导。
但是如果说这里大标题就是二次型，则Q一定是对称的（可以证明），那么这里分出Q为“常数矩阵”这样的说法不合适。
我建议此处标题改为“形如xTQx的多元函数”更为合适，然后分成Q为常数矩阵/对称矩阵考虑求导。

**Comment by Visualize-ML** [comment]
谢谢你！确实不准确，你是对的。

请继续批评。Cheers,
James
