### ISSUE TITLE
矩阵力量的向量空间一章，八大公理处

### ISSUE THREAD

**Issue by Cynthian-pshds** [Visualize-ML/Book4_Power-of-Matrix#172]
“分配律”疑讹作“分配率”
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/169544812/1821256e-9893-49be-beba-c1a41d68588d)

**Comment by Visualize-ML** [comment]
确实写错了，请继续批评指正。

Cheers,
