### ISSUE TITLE
Page 6 | Chapter 10 数据投影 | 字符缺失

### ISSUE THREAD

**Issue by neverland7** [Visualize-ML/Book4_Power-of-Matrix#18]
![image](https://user-images.githubusercontent.com/44805723/234884560-28ee4d71-8462-46d3-bbb1-cc7c4c18c7c2.png)
图5上面的一段话中，圈中应为
$z_{i,j}$

**Comment by Visualize-ML** [comment]
谢谢你！请继续批评。
