### ISSUE TITLE
Figure numbering problem

### ISSUE THREAD

**Issue by woodwm** [Visualize-ML/Book4_Power-of-Matrix#2]
`/Book4_Ch19_直线到超平面__矩阵力量__从加减乘除到机器学习.pdf`

On page 4, the reference to figure 2 and the figure number are not consistent. 
![image](https://user-images.githubusercontent.com/13971199/183431619-e3066c2b-e344-4d72-9bd2-de7d6e04c0f5.png)

The page numbering is also strange as it is not continuous.

**Comment by Visualize-ML** [comment]
谢谢！已经修改，并更新文件。欢迎多提问题、意见。
