### ISSUE TITLE
Book4_Ch15_奇异值分解 page 13

### ISSUE THREAD

**Issue by ZorAttC** [Visualize-ML/Book4_Power-of-Matrix#20]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/93999826/235829715-ad16563a-7ab2-468b-ad1c-2ffb09fe40f7.png">

拼写错误 "srqt"->"sqrt"

**Comment by ZorAttC** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/93999826/235830809-e9564cb4-6ebc-4218-9065-98a72b6150c8.png">
最后一句话可能存在错误，“通过叠加还原原始数据矩阵”

**Comment by Visualize-ML** [comment]
谢谢你！后面统一修改。请继续批评

**Comment by Visualize-ML** [comment]
谢谢你！已经修改
