### ISSUE TITLE
Book4_Power-of-Matrix/Book4_Ch16_深入奇异值分解 page14

### ISSUE THREAD

**Issue by ZorAttC** [Visualize-ML/Book4_Power-of-Matrix#21]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/93999826/235840729-1538b149-68f8-439f-9d23-908e50736144.png">
下标错误，由配图可知下标应为[v1,v2......vd]

**Comment by Visualize-ML** [comment]
谢谢你！又是复制粘贴偷懒..

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改。 Gmail把你的邮件归类错了 ，抱歉回复晚了。请继续批评指正。
