### ISSUE TITLE
Page 16 | Chapter 2 向量运算 >向量减法-优化

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#23]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/1775dd34-674a-44a4-a49c-f2ee208feaf3)

### 问题分析:
一般而言, 只有 **起点为原点** 的向量, 才能用 **指向某点的向量**  缺省代称
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/c2a70577-ddf5-413c-8952-98d7505c7414)
上图摘自 Page 4 | Chapter 2 向量运算

### 改进建议:
向量 **a** 减去向量 **b**，得到向量 **a** – **b**,其对应箭头 从  向量**b**的终点   指向   向量**a**的终点

**Comment by lgr1230** [comment]
原本想用类似:

向量 **a-b** 对应箭头,
**起点:**  向量b的终点
**终点:**  向量a的终点  

但感觉初见, 反而会更让人糊涂(谁的起点?谁的终点?)
就选择了 **从......指向......** 的说明格式

**Comment by Visualize-ML** [comment]
谢谢！确实需要修改表述。

Cheers,
James
