### ISSUE TITLE
本系列丛书书名没有更改

### ISSUE THREAD

**Issue by zhangshuiyong** [Visualize-ML/Book4_Power-of-Matrix#24]
Book4_Ch06_分块矩阵__矩阵力量__从加减乘除到机器学习.pdf
第5页/"大家将会在本书第 22 章，以及本系列丛书《概率统计》和《数据科学》两册中看到图 2 这种分块方式的用途。"
第20页/"分块矩阵的逆将会用在协方差矩阵上，特别是在求解条件概率、多元线性回归时。本系列丛书《概率统计》一则会深入探讨这一话题"

**本系列丛书这两本书名应该修改了，以上没修改**

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改。请继续批评指正。

Cheers,
James

**Comment by Visualize-ML** [comment]
谢谢你，回复晚了。你的邮件被Gmail分类错了。这个问题已经在纸质书上修改了。请继续批评指正。
