### ISSUE TITLE
图例列数保持为3列可能更好

### ISSUE THREAD

**Issue by zhangshuiyong** [Visualize-ML/Book4_Power-of-Matrix#25]
Book4_Ch06_分块矩阵__矩阵力量__从加减乘除到机器学习.pdf/图7/图8

**最好和全文保持一致，输出的ai*b(i)矩阵的列数保持为3列**

![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/1655233/7367f943-1375-4500-be81-d2a23e495d97)

![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/1655233/100d4c31-d2ce-4865-8f3f-8e023c13f55e)

**Comment by Visualize-ML** [comment]
你是对的，这幅图存在错误，纸质书已经修改。

Cheers,
James
