### ISSUE TITLE
Page 29 | Chapter 2 向量运算 小瑕疵

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#30]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/3e1fa449-5b7e-4019-902f-e5f889f2801c)

向量积 (   **_是_**   )  一种“向量 → 向量”的运算规则。

**Comment by Visualize-ML** [comment]
谢谢你！请继续批评。

Cheers,
