### ISSUE TITLE
Page 13 | Chapter 13 特征值分解 小瑕疵

### ISSUE THREAD

**Issue by HairlessVillager** [Visualize-ML/Book4_Power-of-Matrix#31]
“谱分解格拉姆矩阵”下面的格拉姆矩阵的定义`G=X^TX`应该是斜体加粗，但是第二个`X`没有斜体

**Comment by HairlessVillager** [comment]
![VfOBsH.png](https://i.328888.xyz/2023/05/19/VfOBsH.png)

**Comment by Visualize-ML** [comment]
谢谢你！请继续批评。

Cheers
