### ISSUE TITLE
Page 20 | Chapter 9 正交投影 图片描述错误

### ISSUE THREAD

**Issue by HairlessVillager** [Visualize-ML/Book4_Power-of-Matrix#32]
图 13 描述错误，原描述为“格拉姆-施密特正交化第**三**步”，但是根据图上的内容推断，图上正在进行`eta_2`的计算，所以建议修改为“格拉姆-施密特正交化第**二**步”

![V4CsAN.png](https://i.imgloc.com/2023/05/21/V4CsAN.png)

**Comment by Visualize-ML** [comment]
谢谢你，这一处确实错了！后面将统一修改。

请继续批评指正。

Cheers,
James
