### ISSUE TITLE
本书中 "外积" 有无精确对应? 

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#35]
### 问题起因:
Page 18 | Chapter 4 矩阵 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/3bbd97c1-a8a0-4b5b-90e7-1d715a45a181)
**外积展开**:  向量->矩阵,再求和

### 发现问题:
Page 2 | Chapter 2 向量运算 中
![屏幕截图 2023-05-22 153445](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/6fa10d4a-b13a-4d0a-8c82-b34325df61da)
Page 29 | Chapter 2 向量运算 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/b7ac1086-c7a8-4705-873e-2fd47846692c)
Page 34 | Chapter 2 向量运算 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/b5272a69-cbf4-4c46-ac01-f55275aba51a)

所以,本书 到底将"**外积**"对应什么? 
**叉积**? 还是**张量积**?
或者说, 没有标准, **根据上下文**灵活处理?

### [维基百科-外积(消歧义)](https://zh.wikipedia.org/wiki/%E5%A4%96%E7%A9%8D_(%E6%B6%88%E6%AD%A7%E7%BE%A9)):
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/9bd0156e-d5af-4775-a1f6-7b6344145600)

**Comment by Visualize-ML** [comment]
这一处确实麻烦，我会专门说明。鸢尾花书，一般会用张量积这个名称。

请继续批评。

Cheers,
James

**Comment by Visualize-ML** [comment]
外积展开，是习惯说法，应该不会修改。
