### ISSUE TITLE
13章-Page17-谱分解图11-@号的概念一直是相乘，图中应该是+号？

### ISSUE THREAD

**Issue by zhangshuiyong** [Visualize-ML/Book4_Power-of-Matrix#36]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/1655233/132429da-ed12-4c71-adf6-60ad9f512c71)

**Comment by Visualize-ML** [comment]
纸质书已经修改，谢谢批评指正。

Cheers,
James
