### ISSUE TITLE
Book4_Ch01_向量__矩阵力量 page4

### ISSUE THREAD

**Issue by soundsoul** [Visualize-ML/Book4_Power-of-Matrix#37]
“行向量、列向量” 章节
“反向来看” 段落
X 任一 " 行向量 --> 列向量"  (x(1)、x(2)、…、x(150)) 代表一朵鸢尾花样本花萼长度、花萼宽度、花瓣长度和花瓣宽度测量结果。而X某一 " 列向量 --> 行向量" (x1、x2、x3、x4) 为鸢尾花某个特征的样本数据。

**Comment by Visualize-ML** [comment]
这个没错，行向量代表特定样本；列向量代表特定特征。
