### ISSUE TITLE
数学符号的疑惑(个人感受)

### ISSUE THREAD

**Issue by Yjsmall** [Visualize-ML/Book4_Power-of-Matrix#40]
当我阅读第二章向量运算的张量积这一节时候,面对@符号,以为是写错了,因为这里没有任何描述性语言来说这个符号@,我感觉这里文中所说"a$\otimes$b可以写成两种形式",并没有很好的让我意识到图中@是第二种形式,而是让我感觉是不写错了,因为上面公式体现两者不同形式也是以符号$\otimes$来体现的.纸质书P53页(电子书Ch02 P36页)
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/56305848/beec7a59-31e0-40f7-8911-b4a5040eb9b9)
但是往后翻书就找到这个符号的定义了.是张量的第二种形式
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/56305848/f38ce389-f68c-449d-91b5-52a483a7104e)
这个图中的等号就很好说明两者是相等的,但是它出现位置是在纸质书的111页.

**Comment by Visualize-ML** [comment]
谢谢你的来信，抱歉给你带来困扰。确实上下文在交代符号时，应该更清楚一些！

请继续批评！Cheers
James
