### ISSUE TITLE
Ch 18 P20 引入B^(-1/2)的原因是什么呢？

### ISSUE THREAD

**Issue by haithink** [Visualize-ML/Book4_Power-of-Matrix#41]
Chapter 18 拉格朗日乘子法Page 20 说“请大家自己将 (45) 代入 (43)，并完成推导”，这里代入43， 并没有得到什么化简的结果（是我没看出来？），那么 引入B^(-1/2)的原因是什么呢？ 把问题转化为公式（35）的形式吗？

**Comment by 17314796423** [comment]
我看到这里表示有相同的疑惑

**Comment by Visualize-ML** [comment]
18.43就化简完了，这样形式上就是瑞利商了，分子yTy，分母yT和y中间的一坨矩阵乘法的结果做EVD就找到瑞利商最大最小值。

**Comment by 17314796423** [comment]
明白了，感谢答疑

**Comment by haithink** [comment]
> 18.43就化简完了，这样形式上就是瑞利商了，分子yTy，分母yT和y中间的一坨矩阵乘法的结果做EVD就找到瑞利商最大最小值。
> […](#)

哦，忘了回复了。目的就是是为了转换形式为（35）。校正下您的回复：分目yTy，分子yT和y中间的一坨矩阵乘法。
