### ISSUE TITLE
纸质书图片印刷错误

### ISSUE THREAD

**Issue by Yjsmall** [Visualize-ML/Book4_Power-of-Matrix#43]
纸质书的 P100(第四章） 这里的图片的红色向量箭头不正确。
但是电子版图片是正确的。
![IMG_4145](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/56305848/9df4f8f0-d1a6-441a-a1df-6222aefde5d7)

**Comment by Visualize-ML** [comment]
谢谢你！请继续批评指正！

Cheers
