### ISSUE TITLE
ch 22 公式(24)符号错误

### ISSUE THREAD

**Issue by Moneyna** [Visualize-ML/Book4_Power-of-Matrix#44]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/38501740/b2e2cf65-e01c-400d-97dc-f61a470bdf94)
似乎应该是I-2/n(11^T)+1/n11^T，而不是I-2/n(11^T)-1/n11^T?

**Comment by Visualize-ML** [comment]
谢谢你，符号确实错了。已经记录下来，请继续批评。

Cheers,
James
