### ISSUE TITLE
纸质书P305最下面式(12.33)中应该为r1、r2、r3，最后一个r2应该更改为r3.

### ISSUE THREAD

**Issue by Man-Yacan** [Visualize-ML/Book4_Power-of-Matrix#45]
纸质书P305最下面式(12.33)中应该为r1、r2、r3，最后一个r2应该更改为r3.

**Comment by Man-Yacan** [comment]
纸质书P305最下面式(12.33)中应该为r1、r2、r3，最后一个r2应该更改为r3.

**Comment by Visualize-ML** [comment]
谢谢你！确实写错了，请继续批评。

Cheers
James
