### ISSUE TITLE
建议：关于电子版的图片跳转位置问题

### ISSUE THREAD

**Issue by SuperShook** [Visualize-ML/Book4_Power-of-Matrix#5]
感谢细心在 图X 中还能插入超链接跳转，但是跳转位置都是图脚注了，每次都需要手动翻上去。
希望可以在后续编写新书时咱可否换个位置，偏上一点?
我知道电子版目前都还是免费的，有点吹毛求疵了。

**Comment by SuperShook** [comment]
另外，在正式版的书籍中可否在
不同本书中的互相引用时加入脚注，标明出自于被引书的哪页？

**Comment by Visualize-ML** [comment]
谢谢你的建议！为了保证最后出图都是矢量，打印成PDF时，所有的插图跳转连接都丢失了。希望理解。
正式出版物中，会参考你的建议，引用时加入页码。
欢迎继续提出建议。
