### ISSUE TITLE
Book4_Ch14_深入特征值分解的一个歧义

### ISSUE THREAD

**Issue by 934236629** [Visualize-ML/Book4_Power-of-Matrix#51]
本章中的 LDL分解：缩放 → 剪切 这一块，（85）式首先说：“A~LD^1/2”，（86）式：“x=LD^1/2”。而两个式子之间有一句话：“A这个映射相当于“先缩放 (D^-1/2),再剪切 (L)”，图12也写明：“y=D^-1/2 z”......所以，D的指数的1/2到底是正还是负产生了歧义。
此外还有一个问题，就是（84）式为什么对AA^T进行LDL分解，而不是像上文特征值分解中，对Q=（AA^T）^(-1)进行分解呢？ 
非常期待姜老师的回复，祝画图顺利！

**Comment by Visualize-ML** [comment]
谢谢你！

1) 确实有歧义，负号标错了，应该删掉。

2) 我们先是对Q特征值分解 (14.71)，然后转化为 AAT的特征值分解 (14.74)。而LDL分解的对象直接为 AAT (14.84)。

整个几何变换是为了配合x = Az，而zTz = 1代表单位圆，xTx = 1代表旋转椭圆。

请继续批评指正。

Cheers,
James
