### ISSUE TITLE
Book4_Ch18

### ISSUE THREAD

**Issue by superwjfeng** [Visualize-ML/Book4_Power-of-Matrix#6]
您好
Book4_Ch18公式25，即KKT条件的第一个式子多了一个 $\lambda$
不应该是 $\nabla f(\boldsymbol{x})+\lambda_h\nabla h({\boldsymbol{x}})+\lambda_g\nabla g({\boldsymbol{x}})\lambda=0$ 吧？
应该是 $\nabla f(\boldsymbol{x})+\lambda_h\nabla h({\boldsymbol{x}})+\lambda_g\nabla g({\boldsymbol{x}})=0$

**Comment by Visualize-ML** [comment]
谢谢！确实多了一个lambda，已经修改。欢迎继续提意见
