### ISSUE TITLE
Book4_Ch18.2_等式约束条件_梯度平行

### ISSUE THREAD

**Issue by LeeElvis** [Visualize-ML/Book4_Power-of-Matrix#63]
图4下方段落中第二行，语句：‘容易发现 $-\nabla f(\mathbf{x})$ 在 $h(\mathbf x)$方向，在 $f(\mathbf x)$ 减小方向存在投影分量’ 该语句不通顺，可以改为：容易发现 $-\nabla f(\mathbf{x})$也就是 $f(\mathbf x)$ 减小方向，在 $h(\mathbf x)$方向存在投影分量。

**Comment by Visualize-ML** [comment]
确实不通顺，谢谢你。下一版会修改，请继续批评指正。

Cheers,
James
