### ISSUE TITLE
Page 4 | Chapter 7 向量空间  错字

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#64]
**率 -> 律**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/dcb840f4-cf8c-419f-af3c-04c9a08e7876)

实体书也有这个问题

**Comment by Visualize-ML** [comment]
谢谢你，这两个错字没改错来。请继续批评指正。
