### ISSUE TITLE
Page 19 | Chapter 7 向量空间 印刷错误

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#65]
**e1+e2 不一致**

**pdf:**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/c971d915-3edf-4735-b3de-1d4cffea795c)
**实体书:**
![IMG_20230726_002806_edit_2931656938117767](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/c7b07e29-b79e-4f45-8751-d3cfbafd2d24)

**Comment by Visualize-ML** [comment]
纸质书确实错了，请继续批评。谢谢
