### ISSUE TITLE
Page 15 | Chapter 12 Cholesky分解 印刷不一致且错误

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#66]
**pdf:**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/f23f22c8-c77c-4957-9eba-549ea0ebb780)
**实体书:**
![IMG_20230726_003944_edit_2932155955659357](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/0d980b8d-fa32-4ab8-a420-007d2009c221)

实体书多了红线这一句,是**冗余**(这句之前点出来了)且**错误**(应该是 不满秩)的

**Comment by Visualize-ML** [comment]
确实错误且冗余。请继续批评指正。
