### ISSUE TITLE
Page 3 | Chapter 13 特征值分解 印刷大小写错误

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#67]
**pdf:**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/501b995a-ab80-4900-b5c5-6368fd55a8ee)
**实体书:**
![IMG_20230726_004751_edit_2932388464113489](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/e6692c5f-c329-4907-88f9-2211859be363)

**Comment by Visualize-ML** [comment]
确实错了，应该是小写w。请继续批评指正，谢谢。
