### ISSUE TITLE
Page 13 | Chapter 13 特征值分解 

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#68]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/f1b3d6d6-7a2a-4938-b1d5-cfb4652360b5)
yj?**单位矩阵???**

**Page 8 | Chapter 9 正交投影 中**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/a63c1a4a-059d-456f-bfaf-80ff058d8a48)

要么改成
**V是正交矩阵**
要么改成
**vj是单位向量(推荐,且本意应该是这个)**

**Comment by Visualize-ML** [comment]
确实写错了，应该是v_j
