### ISSUE TITLE
Page 12 | Chapter 14 深入特征值分解 

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#69]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/7ce8fa83-4dda-4670-a791-29474a0e96aa)

应该为
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/0dc01f5d-01f2-4c45-abcd-9c2093ac37b6)

**理由:**
Page 12 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/66c7734c-f7fc-442f-917d-a91f6f35467c)
Page 13 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/5af963f6-1caa-4b33-bffe-c21790d9e937)

以及,我验算了

**Comment by Visualize-ML** [comment]
谢谢你，确实写反了，已经记下。请继续批评指正。对了，把你的邮寄地址再发我邮箱一遍，《统计至简》样书
