### ISSUE TITLE
Page 27 | Chapter 5 矩阵乘法

### ISSUE THREAD

**Issue by yaozhj8** [Visualize-ML/Book4_Power-of-Matrix#70]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/106165022/c0f168fd-59ad-48e4-a9a9-106c8846879b)
这里的 $\vec{v}$ 没说明是单位向量，求‘坐标’的话是不是还要除以 $||\vec{v}||$

**Comment by Visualize-ML** [comment]
谢谢你，确实要指出v为单位列向量。请继续批评指正。

Cheers,
James
