### ISSUE TITLE
Page 6 | Chapter 18 拉格朗日子乘法 前后文不对应

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#78]
**pdf:**
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/ecf8fe2f-eff1-44e8-a174-3ee871bdb781)
**实体书:**
![IMG_20230812_194726_edit_4153968103372403](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/e0a9fb66-0e30-4298-ab45-0b5fbcaa1471)

**Comment by Visualize-ML** [comment]
确实应该是，18.3。请继续批评指正，谢谢。
