### ISSUE TITLE
Page 19 | Chapter 18 拉格朗日子乘法 

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#79]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/44b13a42-4209-4316-be7a-957cc2f9ad6f)

Page 18 中:
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/3338e0a1-8859-4017-9f91-f5b5b974475b)
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/579a3a8b-1b5e-4b3f-b0d9-464d541af8a2)

所以应该是B=I时,对应的应该是 **式32**

**Comment by Visualize-ML** [comment]
火眼金睛，确实标错了。请继续批评指正，谢谢。
