### ISSUE TITLE
Page 6 | Chapter 20 再谈圆锥曲线 下标错误

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#81]
![屏幕截图 2023-08-12 210027](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/2a7d6483-f89f-40e2-ae5e-93d04e6be975)

两个**x1-c2**

**Comment by Visualize-ML** [comment]
确实错了，请继续批评指正，谢谢。
