### ISSUE TITLE
Page 18 | Chapter 21 曲面和正定性 疑惑/错误?

### ISSUE THREAD

**Issue by lgr1230** [Visualize-ML/Book4_Power-of-Matrix#82]
### 问题段落:
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/3f33ac35-38e8-4577-a20b-25dec7c6b31b)

### 论证过程:
又 Page 17 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/291a4a42-cb96-4d6d-bfb6-8332fdf65f03)

当A的行列式值大于0 ,即ac > (b的平方) >=0,也就是说,ac>0

又 Page 5 中
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/beb1de32-6d8c-4af7-b306-1a96446ee372)
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/477d3770-759f-4ece-9779-90175ee6bc90)
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/69034009/5f274ba1-45c3-4fbe-bc41-0e1c607db27d)

可以得到,A的两个特征值( a 和 c )同号
进一步得到,A正定或负定

但如果按照第一张图中划线部分来推论的话,
可以得到, ac>0
但是无法进一步得到 |A| >0 
**当 (b的平方)大于ac 时,划线原文不成立**

当然,不排除我学艺不精,闹了笑话的可能,所以标题没有直接断言是错误

**Comment by Visualize-ML** [comment]
是不是忽略了等式，lambda_1 * lambda_2 = ac - b^2。

**Comment by lgr1230** [comment]
好的,确实是我的问题
我学艺不精, 错将矩阵A的主对角线上的元素（ａ和ｃ）,不假思索地当成了其特征值

翻阅之后,找到了相关知识点, 在本书　**13.3**　处,提到了:
### 矩阵A的行列式值 = 矩阵A对应的特征值矩阵 的行列式值
而特征值矩阵是**对角矩阵**,且所有特征值依次落于其主对角线上
也就是说，
### 如果矩阵A能进行特征值分解，则A的行列式值等于A的所有特征值之积

感谢解惑

**Comment by Visualize-ML** [comment]
闻道有先后！大家一起进步。

祝好
