### ISSUE TITLE
【Book4_Chapter2.11_Page53】 图2.31 张量积符号

### ISSUE THREAD

**Issue by daisir035** [Visualize-ML/Book4_Power-of-Matrix#84]
![image](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/73103297/93d3a137-4461-4c03-b104-827f674642ed)

**Comment by Visualize-ML** [comment]
谢谢你，这一处的意思是 a  ⊗  b = a @ b^T 两者等价。请继续批评指正。

Cheers,
