### ISSUE TITLE
纸质书Page 71 | Chapter 3 标准化欧式距离表达不一致

### ISSUE THREAD

**Issue by gamegirl008** [Visualize-ML/Book4_Power-of-Matrix#85]
这一页的标准化欧氏距离中的对角矩阵D的定义是对角线上的元素为每个特征的方差，但是在《统计至简》中的Chapter23中的标准化欧氏距离对角矩阵的D的定义却是对角线上的元素为每个特征的标准差。虽然意义是一样的，但对于初学者来说容易搞混，一个系列中的表述应该尽量一致。

**Comment by Visualize-ML** [comment]
谢谢你的建议。整套书对于记号做了几次统一，但是还有漏网之鱼。请多多批评指正！

Cheers,
