### ISSUE TITLE
Page 4 | Chapter 1 行向量列向量写反了，图里的矩阵也反了

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [Visualize-ML/Book4_Power-of-Matrix#86]
Page 4 | Chapter 1 
1. 行向量列向量写反了
2. 图里的矩阵也反了，应该是150行4列
3. 坐标系画的不准确，因为不管每一行还是每一列的数据，都不是三维的，所以不应该使用三维坐标系。

**Comment by Visualize-ML** [comment]
谢谢你。这幅图三根箭头不代表三维坐标系。这一点确实需要修改，以避免误会。

150个行向量代表，150个散点。
4个列向量代表，四个方向。

请继续批评指正。

Cheers
