### ISSUE TITLE
建议：保留 pdf 版本的结论公式蓝色方框指示

### ISSUE THREAD

**Issue by WinfredLu** [Visualize-ML/Book4_Power-of-Matrix#89]
如图。
印刷版似乎没有这个方框。个人感觉有了这个方框把公式和过程区分开，对于快速翻阅（比如以复习为目的地阅读）而言方便不少。
![图片](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/122422616/4d441c0d-53b3-4bd3-9548-a89151f7fb29)

**Comment by Visualize-ML** [comment]
谢谢你，纸质版排版的时候把这个设计拿掉了。如果很多读者觉得有必要，后续可以补回来。请继续批评指正！
