### ISSUE TITLE
Book4_Ch12_Cholesky Page15-16

### ISSUE THREAD

**Issue by Hurricane-k** [Visualize-ML/Book4_Power-of-Matrix#9]
Eq.(39)下面，正定矩阵满秩，这种情形**P**不可以Cholesky分解。
Eq.(43)下面，上式中两个都不能进行Cholesky分解，因为**P**都不满秩。

两处存在矛盾，根据上下文，应该是正定矩阵满秩，这种情况才可以Cholesky？

**Comment by Visualize-ML** [comment]
谢谢你的批评！Eq (39) 解释的不清楚，已经修改。简单来说，只有正定矩阵才能Cholesky分解。而正定必然满秩。显然不满秩的方阵，不能Cholesky分解。

**Comment by Visualize-ML** [comment]
欢迎继续批评

**Comment by Hurricane-k** [comment]
您謙虛了 您的內容對我幫助很大 有在繼續閱讀 若有文中存在一定表達問題的 會再指出的 謝謝您的無私分享
