### ISSUE TITLE
建议：图2.25 向量叉乘右手定则更换示例图

### ISSUE THREAD

**Issue by WinfredLu** [Visualize-ML/Book4_Power-of-Matrix#91]
如图。私以为图中的手形图形不能很好地表现向量叉乘右手定则具体信息。我在网上照了一张可能比较适合的示意图，或许可以更好地传达视觉信息。
![微信图片_20230904195858](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/122422616/7dca84e4-b52f-47af-a50f-0b3582d96368)
![图片](https://github.com/Visualize-ML/Book4_Power-of-Matrix/assets/122422616/15134d08-f5bd-4fe5-8f49-57d991f39c18)

**Comment by Visualize-ML** [comment]
谢谢你，你建议的手势用在了《数学要素》三维直角坐标系中。
